plt.subplot(1, 2, 2)
top_20_production_revenue.plot(kind='bar', color='skyblue')
plt.title('Top 20 des Sociétés de Production avec les Revenus Ajustés les Plus Élevés')
plt.xlabel('Société de Production')
plt.ylabel('Revenu Ajusté Total')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y')

plt.tight_layout()
plt.show()
